name: Fuzzing for HTML
on:
  push:
    branches: [ "main" ]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Temurin is the recommended OpenJDK distribution
          java-version: '17'
          
      - name: Compile Fuzzer
        run: javac Fuzzer.java

      - name: Fuzztest
        run: java Fuzzer "./html_parser_linux_x86_64"
        env:
          PATH: ${{ github.workspace }}:$PATH
    continue-on-error: false